### PR TITLE
Updated Information

### PR DESCRIPTION
**Pull request by cr2007**
Changes:
- Updates the process for accessing the MACS SSH Servers
Since the recent [IS Security Incident](https://www.hw.ac.uk/uk/services/is/system-status.htm) that happened in late March to mid-April, the process to access the SSH Servers have become more secure, including entering a verification code with the launch of [Multi-Factor Authentication (MFA)](https://www.hw.ac.uk/uk/services/is/it-essentials/multi-factor-authentication.htm) last semester.
- Adds a card in the [Exam](https://myhwu.com/#exam) area to include the [Assessment Results](https://www.hw.ac.uk/uk/students/studies/examinations/results.htm) page
Includes the dates for when the assessment results arrive

If there are any changes that you want to add to these commits, be it simplifying the SSH process
Feel free to add them.

Regards,
@cr2007

### CODE REVIEW

**Review by alakbarz — APPROVED** [review]
_Ah it was so much easier back in the day..._

Looks good!

**Comment by humaidq** [comment]
Looks good to me! Merging.

**Comment by humaidq** [comment]
Thanks Chandrashekhar for keeping portal up to date! :smiley:

**Comment by cr2007** [comment]
This [portal](https://myhwu.com/) has honestly been a life saver in many situations.
In just quickly accessing any particular service in particular

Glad I could be a part of this by contributing from my side 😌

**Pull request merged**
